cam_model: Pinhole # 针孔相机
cam_width: 1280 # 图像宽度
cam_height: 1024 # 图像高度
scale: 0.5 # 图像缩放因子
cam_fx: 1293.56944 # x方向焦距
cam_fy: 1293.3155 # y方向焦距
cam_cx: 626.91359 # 主点x坐标
cam_cy: 522.799224 # 主点y坐标
cam_d0: -0.076160 # 一阶径向基变系数k1
cam_d1: 0.123001 # 二阶径向畸变系数k2
cam_d2: -0.00113 # 三阶径向畸变系数k3
cam_d3: 0.000251 # 四阶径向畸变系数k4