common:
  img_topic: "/left_camera/image"
  lid_topic: "/livox/multi_lidar"  # 使用合并后的LiDAR话题
  imu_topic: "/livox/imu_192_168_1_159"  # 默认使用159的IMU
  external_imu_topic: "/novatel/oem7/odom"  # 如果有外置IMU，可以在这里设置话题
  img_en: 0
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  extrinsic_T: [-0.011, -0.02329, 0.04412]
  extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  Rcl: [0.00610193,-0.999863,-0.0154172,
        -0.00615449,0.0153796,-0.999863,
        0.999962,0.00619598,-0.0060598] 
  Pcl: [0.0194384, 0.104689,-0.0251952]

time_offset: 
  imu_time_offset: 0.1
  img_time_offset: 0.1
  exposure_time_init: 0.0

preprocess:
  point_filter_num: 1 
  filter_size_surf: 0.5 # 体素滤波大小
  lidar_type: 1 # Livox Avia LiDAR
  scan_line: 6 # Avia: 6, Mid360: 4
  blind: 0.8

# 视觉里程计
vio:
  max_iterations: 5
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000 
  patch_size: 8
  patch_pyrimid_level: 4
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1

# imu参数      
imu:
  imu_en: true
  imu_int_frame: 100
  acc_cov: 0.5 # 0.2
  gyr_cov: 0.3 # 0.5
  b_acc_cov: 0.0001 # 0.1
  b_gyr_cov: 0.0001 # 0.1

# 激光雷达里程计
lio:
  max_iterations: 5
  dept_err: 0.02
  beam_err: 0.05
  min_eigen_value: 0.0025 # 0.005
  voxel_size: 1 # 体素底图尺寸
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]
  sigma_num: 3

local_map:
  map_sliding_en: true
  half_map_size: 1000
  sliding_thresh: 10

uav:
  imu_rate_odom: true
  gravity_align_en: false
  elevation_axis: "-x"  # 可选值: "x", "-x", "y", "-y", "z", "-z"

publish:
  dense_map_en: false
  pub_effect_point_en: true
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0
  publish_cloud_body: false  # 是否发布body坐标系下的点云

evo:
  seq_name: "CBD_Building_01"
  pose_output_en: false

lidar_save:
  save_en: false
  effect_save_en: false
  laz_save_en: true
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: 1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

external_imu:
  enable: true
  weight: 0.5  # 外置IMU权重(0-1)