common:
  img_topic: "/left_camera/image"
  lid_topic: "/livox/multi_lidar"  # 使用合并后的LiDAR话题
  imu_topic: "/livox/imu_192_168_1_159"  # 默认使用159的IMU
  external_imu_topic: "/novatel/oem7/odom"  # 如果有外置IMU，可以在这里设置话题
  img_en: 0
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  extrinsic_T: [-0.011, -0.02329, 0.04412]
  extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  Rcl: [0.00610193,-0.999863,-0.0154172,
        -0.00615449,0.0153796,-0.999863,
        0.999962,0.00619598,-0.0060598] 
  Pcl: [0.0194384, 0.104689,-0.0251952]

time_offset: 
  imu_time_offset: 0.1
  img_time_offset: 0.1
  exposure_time_init: 0.0

preprocess:
  point_filter_num: 1
  filter_size_surf: 0.25 # 体素滤波大小
  lidar_type: 1 # Livox Avia LiDAR
  scan_line: 6 # Avia: 6, Mid360: 4
  blind: 0.8

# 视觉里程计
vio:
  max_iterations: 5
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000 
  patch_size: 8
  patch_pyrimid_level: 4
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1
  capacity: 0 # LRU cache capacity for visual feature map (0 = disable LRU cache)

# imu参数      
imu:
  imu_en: true
  imu_int_frame: 30
  acc_cov: 0.5 # 0.2
  gyr_cov: 0.3 # 0.5
  b_acc_cov: 0.0001 # 0.1
  b_gyr_cov: 0.0001 # 0.1

# 激光雷达里程计
lio:
  max_iterations: 5
  dept_err: 0.02
  beam_err: 0.05
  min_eigen_value: 0.0025 # 0.005
  voxel_size: 1 # 体素底图尺寸
  max_layer: 2
  max_points_num: 64
  layer_init_num: [1, 1, 1, 1, 1]
  sigma_num: 3
  capacity: 10000  # LRU缓存容量, 越大占用内存越多 (0 = 禁用LRU缓存)

# Pillar Voxel 参数配置
pillar_voxel:
  pillar_voxel_en: true
  min_adjacent_num: 2      # 相邻地面体素数量阈值
  elevation_axis: "z"  # 可选值: "x", "-x", "y", "-y", "z", "-z"

local_map: 
  map_sliding_en: false
  half_map_size: 1000
  sliding_thresh: 8

uav:
  imu_rate_odom: true
  gravity_align_en: true

publish:
  dense_map_en: true
  pub_effect_en: true
  pub_plane_en: false
  pub_body_en: false  # 是否发布body坐标系下的点云
  pub_voxel_points_en: true
  pub_scan_num: 1 
  blind_rgb_points: 0.0

evo:
  seq_name: "CBD_Building_01"
  pose_output_en: false

lidar_save:
  save_en: false
  laz_save_en: true
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: 1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

external_imu:
  enable: true # 是否启用外置IMU
  external_imu_init_frame : 30  # 用于外置IMU初始化的帧数
  time_offset: 0  # 外置IMU时间偏移(秒)
  buffer_size: 100000  # external IMU buffer大小
  external_R : [0, 0, -1, 1, 0, 0, 0, -1, 0]
  external_T : [0, 0, 0]
  external_imu_only: false # 是否
